services:
  db:
    image: postgres:14
    restart: always
    tty: true
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db-data:
